name: sample-nodejs
services:
- build_command: npm run build
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-nodejs
  name: sample-nodejs
